---
title: "Practical Biological Data Analysis"
site: distill::distill_website
preview: img/rbi-twitter-card.png
---


```{r setup, include = FALSE, eval = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Practical Biological Data Analysis with R and RStudio

**Participation in this course requires completion of an assignment prior to the course start date (see the Prerequisites section).**

## Overview

In this short course you will learn to analyze and visualize complex data sets using the R statistical programming language, the RStudio IDE and new tools available in the "tidyverse”. We will focus on key analysis skills and foundational programming concepts necessary for the efficient and reproducible analysis of biological data sets.

## Organization and Contacts 

Kent Riemondy (Director, Instructor): kent.riemondy@cuanschutz.edu 

Michael Kaufman (Instructor):  michael.kaufman@cuanschutz.edu

Ryan Sheridan (Instructor): ryan.sheridan@cuanschutz.edu 

Kristen Wells-Wrasman (Instructor): kristen.wells-wrasman@cuanschutz.edu

The course (2 credit hours) consists of 13 2 hour classes held Mon through Fri from Nov 30 through Dec 16 from 8:00 -10:00 am. The course is tentatively scheduled to be held in the Strauss Health Science Library  (V23) in the HS Library Teaching Lab 2, with a remote option provided. All classes will be recorded and made available through Canvas.

Virtual office hours will also be provided outside of course hours.   

## Goals

Build competence in R so that students use R for data analysis rather than using interactive applications such as Excel or Prism. 
Develop reproducible and efficient data analysis habits.
Introduce data visualization techniques for complex datasets.

## Prerequisites

A personal computer with a common operating system ( macOS, Linux, or Windows), and internet access is necessary to participate in this class. Tablets or iPads will not be supported. Please reach out to us ASAP if you do not have access to a computer, or if you have concerns about the suitability of your device.  There will be a required prerequisite assignment to be completed prior to the start of the course. The assignment will involve installing necessary software, and completion of material providing basic familiarity with R and interacting with the Rstudio IDE. Office hours will be provided prior to the course to assist with any issues that arise with completing the prerequisite assignment. 

## Assignments 

Student's grades will be determined by completion of the prerequisite assignment (10%), class participation (10%), and 4 homework assignments (80%), to be completed by the end of the course.

# Course assistance
 We will provide a Slack workspace for discussion during and after classes, to collaborate, and to get help. In addition the course instructors will hold virtual office hours to provide assistance outside of the course. Please email the course instructors via (`rbi.fellows@cuanschutz.edu`) to schedule a time.
